- name: "Enable HTTP on Firewall"
  firewalld:
    zone: public
    service: http
    state: enabled
    permanent: yes

- name: "Enable HTTPS on Firewall"
  firewalld:
    zone: public
    service: https
    state: enabled
    permanent: yes

  # - name: "Setup SSL in Nginx"
#   lineinfile:
#     path: /etc/nginx/conf.d/default.conf
#     regexp: '^Listen '
#     insertafter: '^#Listen '
#     line: Listen 8080

#     listen 443 ssl;