- name: "Enable HTTP/S on Firewall"
  firewalld:
    zone: public
    service:
      - http
      - https
    state: enabled
    permanent: yes

# - name: "Setup SSL in Nginx"
#   lineinfile:
#     path: /etc/nginx/conf.d/default.conf
#     regexp: '^Listen '
#     insertafter: '^#Listen '
#     line: Listen 8080

#     listen 443 ssl;