- name: Enable EPEL
  become: yes
  yum:
    name: epel-release

- name: Install Deps
  become: yes
  yum:
    name:
      - glib*
      - git
      - unzip
      - tar
      - fail2ban
      - sqlite
      - npm
