---
ansible_ssh_user: root
ansible_ssh_private_key_file: /Users/sivy/.ssh/id_rsa
app_user: bloguser
app_group: blog
github_user: sivy
app_user_private_key: "{{ lookup('env','BLOG_USER_PRIVATE_KEY') }}"

# blog vars
theme_repo: git@github.com:sivy/monkinetic-2020.git
theme_location: /var/goldfrog/monkinetic
content_location: /var/goldfrog/monkinetic-content
content_repo: git@github.com:sivy/monkinetic-2020-content.git

blog_home: "{{ theme_location }}"
blog_posts: "{{ content_location}}/posts"
blog_uploads: "{{ content_location}}/uploads"

blog_auth_user: "{{ lookup('env','BLOG_AUTH_USER') }}"
blog_auth_password: "{{ lookup('env','BLOG_AUTH_PWD') }}"
blog_server_location: "127.0.0.1"
blog_server_port: "8080"
blog_url: "http://monkinetic.blog"

twitter_client_key: "{{ lookup('env','TWITTER_CLIENT_KEY') }}"
twitter_client_secret: "{{ lookup('env','TWITTER_CLIENT_SECRET') }}"
twitter_access_key: "{{ lookup('env','TWITTER_ACCESS_KEY') }}"
twitter_access_secret: "{{ lookup('env','TWITTER_ACCESS_SECRET') }}"

mastodon_client_id: "{{ lookup('env','MASTODON_CLIENT_ID') }}"
mastodon_client_secret: "{{ lookup('env','MASTODON_CLIENT_SECRET') }}"
mastodon_access_token: "{{ lookup('env','MASTODON_ACCESS_TOKEN') }}"

mysql_root_pwd: "{{ lookup('env','MYSQL_ROOT_PWD') }}"

ghost_description: Ghost EM Blog Server
ghost_dist: "https://ghost.org/zip/ghost-latest.zip"
ghost_url: "http://equalmeasures.org"
ghost_home: /var/www/ghost
ghost_log_dir: /var/log/ghost
ghost_mysql_db: "ghostdb"
ghost_mysql_user: "ghostuser"
ghost_mysql_password: "{{ lookup('env','GHOST_PWD') }}"
ghost_port: 2368
ghost_service: ghost-em-blog

ghost_sites:
  -
    ghost_description: Ghost Monkinetic Blog Server
    ghost_url: "http://ghost.monkinetic.blog"
    ghost_home: /var/www/ghost_monkinetic
    ghost_log_dir: /var/log/ghost_monkinetic
    ghost_mysql_db: "ghostdb-monkinetic"
    ghost_mysql_user: "ghost_monkinitic_user"
    ghost_mysql_password: "{{ lookup('env','GHOST_MONKINETIC_PWD') }}"
    ghost_port: 2369
    ghost_service: ghost-monkinetic-blog
  # -
  #   ghost_description: Ghost Anna Blog Server
  #   ghost_dist: "https://ghost.org/zip/ghost-latest.zip"
  #   ghost_url: "http://anna.monkinetic.blog"
  #   ghost_home: /var/www/ghost_anna
  #   ghost_log_dir: /var/log/ghost_anna
  #   ghost_mysql_db: "ghostdb-anna"
  #   ghost_mysql_user: "ghost_anna_user"
  #   ghost_mysql_password: "{{ lookup('env','GHOST_ANNA_PWD') }}"
  #   ghost_port: 2370
  #   ghost_service: ghost-anna-blog

discuss_user: discussuser
discuss_group: discussusers

nodebb_repo: "https://github.com/NodeBB/NodeBB"
nodebb_version: master # "v1.10.x"
nodebb_location: "/var/nodebb"
# nodebb_secret

acme_challenge_type: http-01
acme_directory: https://acme-v02.api.letsencrypt.org/directory
acme_version: 2
acme_email: steveivy@gmail.com
letsencrypt_dir: /etc/letsencrypt
letsencrypt_keys_dir: /etc/letsencrypt/keys
letsencrypt_csrs_dir: /etc/letsencrypt/csrs
letsencrypt_certs_dir: /etc/letsencrypt/certs
letsencrypt_account_key: /etc/letsencrypt/account/account.key
domain_name: monkinetic.blog
acme_domain_names:
  - monkinetic.blog
  - talk.monkinetic.blog
acme_challenge_names:
  -
    domain: monkinetic.blog
    dest: monkinetic.blog
  -
    domain: www.monkinetic.blog
    dest: monkinetic.blog
  -
    domain: talk.monkinetic.blog
    dest: talk.monkinetic.blog

san_domain_names:
  - monkinetic.blog
  - www.monkinetic.blog
  - talk.monkinetic.blog