## DEPRECATED -- Use nginxinc.nginx_config role instead (https://github.com/nginxinc/ansible-role-nginx-config)
---
- name: Deprecation warning
  debug:
    msg: DEPRECATED TASKS -- Use nginxinc.nginx_config role instead (https://github.com/nginxinc/ansible-role-nginx-config)

- name: (DEPRECATED) Find NGINX Configuration Files
  find:
    paths: "{{ item.directory }}"
    patterns: "*.conf"
    recurse: "{{ item.recurse | default(false) }}"
  loop: "{{ nginx_cleanup_config_paths }}"
  when: nginx_cleanup_config_paths is defined
  register: nginx_config_files

- name: (DEPRECATED) Remove NGINX Configuration Files
  file:
    path: "{{ item }}"
    state: absent
  loop: "{{ nginx_config_files.results | default('') | map(attribute='files') | sum(start=[]) | map(attribute='path') | list
        + nginx_cleanup_config_files | default('') }}"
