## DEPRECATED -- Use nginxinc.nginx_config role instead (https://github.com/nginxinc/ansible-role-nginx-config)
---
- name: Deprecation warning
  debug:
    msg: DEPRECATED TASKS -- Use nginxinc.nginx_config role instead (https://github.com/nginxinc/ansible-role-nginx-config)

- name: (DEPRECATED) Ensure HTML Directory Exists
  file:
    path: "{{ item.value.html_file_location | default('/usr/share/nginx/html') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_html_demo_template }}"
  when: nginx_html_demo_template_enable | bool

- name: (DEPRECATED) Dynamically Generate HTML Files
  template:
    src: "{{ item.value.template_file | default('www/index.html.j2') }}"
    dest: "{{ item.value.html_file_location | default('/usr/share/nginx/html') }}/{{ item.value.html_file_name | default('index.html') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_html_demo_template }}"
  when: nginx_html_demo_template_enable | bool

- name: (DEPRECATED) Ensure NGINX Main Directory Exists
  file:
    path: "{{ nginx_main_template.conf_file_location | default('/etc/nginx') }}"
    state: directory
    mode: 0755
  when: nginx_main_template_enable | bool

- name: (DEPRECATED) Dynamically Generate NGINX Main Configuration File
  template:
    src: "{{ nginx_main_template.template_file | default('nginx.conf.j2') }}"
    dest: "{{ nginx_main_template.conf_file_location | default('/etc/nginx') }}/{{ nginx_main_template.conf_file_name | default('nginx.conf') }}"
    backup: yes
    mode: 0644
  when: nginx_main_template_enable | bool
  notify: "(Handler) Run NGINX"

- name: (DEPRECATED) Ensure NGINX HTTP Directory Exists
  file:
    path: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_http_template }}"
  when: nginx_http_template_enable | bool

- name: (DEPRECATED) Ensure NGINX Proxy Cache Directories Exist
  file:
    path: "{{ item.1.path }}"
    state: directory
    owner: "{{ nginx_main_template.user | default('nginx') }}"
    mode: 0755
  with_subelements:
    - "{{ nginx_http_template }}"
    - proxy_cache.proxy_cache_path
    - skip_missing: yes
  when: nginx_http_template_enable | bool

- name: (DEPRECATED) Dynamically Generate NGINX HTTP Configuration Files
  template:
    src: "{{ item.value.template_file | default('http/default.conf.j2') }}"
    dest: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/') }}/{{ item.value.conf_file_name | default('default.conf') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_http_template }}"
  when: nginx_http_template_enable | bool
  notify: (Handler) Run NGINX

- name: (DEPRECATED) Dynamically Generate NGINX Stub Status Configuration File
  template:
    src: "{{ nginx_status_template_file | default('http/status.conf.j2') }}"
    dest: "{{ nginx_status_file_location | default('/etc/nginx/conf.d/status.conf') }}"
    backup: yes
    mode: 0644
  when: nginx_status_enable | bool
  notify: (Handler) Run NGINX

- name: (DEPRECATED) Dynamically Generate NGINX API Configuration File
  template:
    src: "{{ nginx_rest_api_template_file | default('http/api.conf.j2') }}"
    dest: "{{ nginx_rest_api_file_location | default('/etc/nginx/conf.d/api.conf') }}"
    backup: yes
    mode: 0644
  when: nginx_rest_api_enable | bool
  notify: (Handler) Run NGINX

- name: (DEPRECATED) Ensure NGINX Stream Directory Exists
  file:
    path: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/stream/') }}"
    state: directory
    mode: 0755
  with_dict: "{{ nginx_stream_template }}"
  when: nginx_stream_template_enable | bool

- name: (DEPRECATED) Dynamically Generate NGINX Stream Configuration Files
  template:
    src: "{{ item.value.template_file | default('stream/default.conf.j2') }}"
    dest: "{{ item.value.conf_file_location | default('/etc/nginx/conf.d/stream/') }}/{{ item.value.conf_file_name | default('default.conf') }}"
    backup: yes
    mode: 0644
  with_dict: "{{ nginx_stream_template }}"
  when: nginx_stream_template_enable | bool
  notify: (Handler) Run NGINX
