- name: 'Create MyQL Ghost DB {{ item.ghost_mysql_db}}'
  community.mysql.mysql_db:
    login_user: 'root'
    login_password: '{{ mysql_root_pwd }}'
    name: '{{ item.ghost_mysql_db}}'
    state: present

- name: Create MySQL Ghost user
  community.mysql.mysql_user:
    login_user: 'root'
    login_password: '{{ mysql_root_pwd }}'
    name: '{{ item.ghost_mysql_user}}'
    password: '{{ item.ghost_mysql_password }}'
    priv: '{{ item.ghost_mysql_db }}.*:ALL'
    state: present

- name: 'Create Ghost Home in {{ item.ghost_home }}'
  file:
    path: '{{ item.ghost_home }}'
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    mode: ug+rw,o+r
    state: directory

- name: 'Create Ghost logdir in {{ item.ghost_log_dir }}'
  become: yes
  file:
    path: '{{ item.ghost_log_dir }}'
    owner: '{{ app_user }}'
    group: '{{ app_group }}'
    mode: ug+rw,o+r
    state: directory

- name: Download Ghost from ghost.org
  get_url:
    url: "{{ ghost_dist }}"
    dest: /tmp/ghost-latest.tgz
    # force: true

- name: Unarchive Ghost
  become: yes
  become_user: '{{ app_user }}'
  unarchive:
    src: /tmp/ghost-latest.tgz
    dest: '{{ item.ghost_home }}'
    remote_src: true

- name: 'Install Ghost in {{ item.ghost_home }}'
  become: yes
  become_user: '{{app_user}}'
  command: npm install -P
  args:
    chdir: '{{ item.ghost_home}}'
    creates: '{{ item.ghost_home}}/package-lock.json'

- name: 'Create {{ item.ghost_service }} Config'
  become: yes
  become_user: '{{app_user}}'
  template:
    src: config-new.js.j2
    dest: "{{ item.ghost_home }}/config.production.json"

- name: 'Create {{ item.ghost_service }} service'
  template:
    src: ghost-new.service.j2
    dest: '/etc/systemd/system/{{ item.ghost_service }}.service'

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start or Restart Ghost service
  service:
    name: '{{ item.ghost_service }}'
    enabled: yes
    state: restarted
