---
# setup actual blog content

- name: Clone blog files
  become: yes
#   become_user: '{{app_user}}'
  git:
    repo: "{{ theme_repo }}"
    dest: "{{ theme_location }}"
    accept_hostkey: yes
    update: yes

- name: Create Goldfrog Config
  become: yes
  become_user: '{{app_user}}'
  template:
    src: config.yaml.j2
    dest: "{{ blog_home }}/config.yaml"

- name: Start or Restart Goldfrog service
  service:
      name: goldfrogd
      enabled: yes
      state: restarted
