---
# setup actual blog content

- name: Clone blog files
  # become: yes
  git:
    repo: "{{ project_repo }}"
    dest: "{{ project_location }}"
    accept_hostkey: yes
    update: yes

- name: Create Goldfrog Config
  template:
    src: config.yaml.j2
    dest: "{{ blog_home }}/config.yaml"

- name: Start or Restart Goldfrog service
  service:
      name: goldfrogd
      enabled: yes
      state: restarted
