---
    - hosts: webservers

      connection: ssh
      gather_facts: true
      roles:
        - nginxinc.nginx_config

      vars:
        goldfrog_dist: "https://goldfrog-releases.s3-us-west-1.amazonaws.com/goldfrog-latest.tgz"

        nginx_config_http_template_enable: true
        nginx_config_http_template:
          default:
            template_file: http/default.conf.j2
            conf_file_name: default.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              server1:
                server_name: "173.255.215.158 monkinetic.blog www.monkinetic.blog"
                listen:
                  listen_localhost:
                    ip: 0.0.0.0
                    port: 80
                    opts:
                      - default_server

                # ssl_certificate: /etc/letsencrypt/live/example.com/fullchain.pem
                # ssl_certificate_key: /etc/letsencrypt/live/example.com/privkey.pem

                error_page: /usr/share/nginx/html
                client_max_body_size: 10M
                autoindex: false
                reverse_proxy:
                  locations:
                    frontend:
                      location: /
                      proxy_pass: http://goldfrog_server

            upstreams:
              upstream_1:
                name: goldfrog_server
                lb_method: least_conn
                zone_name: frontend
                zone_size: 64k
                sticky_cookie: false
                servers:
                  frontend_server_1:
                    address: 127.0.0.1
                    port: 8080
                    weight: 1
                    health_check: max_fails=3 fail_timeout=5s

          ghost:
            template_file: http/default.conf.j2
            conf_file_name: ghost.conf
            conf_file_location: /etc/nginx/conf.d/
            servers:
              server1:
                server_name: "equalmeasures.org www.equalmeasures.org unequalmeasures.org www.unequalmeasures.org"
                listen:
                  listen_localhost:
                    ip: 0.0.0.0
                    port: 80

                # ssl_certificate: /etc/letsencrypt/live/example.com/fullchain.pem
                # ssl_certificate_key: /etc/letsencrypt/live/example.com/privkey.pem

                error_page: /usr/share/nginx/html
                client_max_body_size: 10M
                autoindex: false
                reverse_proxy:
                  locations:
                    frontend:
                      location: /
                      proxy_pass: http://ghost_server
            upstreams:
              upstream1:
                name: ghost_server
                lb_method: least_conn
                zone_name: frontend
                zone_size: 64k
                sticky_cookie: false
                servers:
                  frontend_server_2:
                    address: 127.0.0.1
                    port: 2368
                    weight: 1
                    health_check: max_fails=3 fail_timeout=5s
