---
- hosts: webservers

  connection: ssh
  gather_facts: true
  roles:
    - base
    - nginxinc.nginx
    - blogserver
    - blogtheme

  vars:
    goldfrog_dist: "https://goldfrog-releases.s3-us-west-1.amazonaws.com/goldfrog-latest.tgz"
    project_repo: https://github.com/sivy/monkinetic-2020.git
    # project_location should be a SUBDIR of /var/goldfrog
    project_location: /var/goldfrog/monkinetic
    content_location: /var/goldfrog/monkinetic-content
    content_repo: https://github.com/sivy/monkinetic-content.git

    blog_home: "{{ project_location }}"
    blog_posts: "{{ content_location}}/posts"
    blog_uploads: "{{ content_location}}/uploads"

    blog_auth_user: "{{ lookup('env','BLOG_AUTH_USER') }}"
    blog_auth_password: "{{ lookup('env','BLOG_AUTH_PWD') }}"
    blog_server_location: "127.0.0.1"
    blog_server_port: "8080"
    blog_url: "http://monkinetic.blog"

    twitter_client_key: "{{ lookup('env','TWITTER_CLIENT_KEY') }}"
    twitter_client_secret: "{{ lookup('env','TWITTER_CLIENT_SECRET') }}"
    twitter_access_key: "{{ lookup('env','TWITTER_ACCESS_KEY') }}"
    twitter_access_secret: "{{ lookup('env','TWITTER_ACCESS_SECRET') }}"

    mastodon_client_id: "{{ lookup('env','MASTODON_CLIENT_ID') }}"
    mastodon_client_secret: "{{ lookup('env','MASTODON_CLIENT_SECRET') }}"
    mastodon_access_token: "{{ lookup('env','MASTODON_ACCESS_TOKEN') }}"

    nginx_http_template_enable: true
    nginx_http_template:
      default:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                ip: 0.0.0.0
                port: 80
                opts:
                  - default_server

            # ssl_certificate: /etc/letsencrypt/live/example.com/fullchain.pem
            # ssl_certificate_key: /etc/letsencrypt/live/example.com/privkey.pem

            server_name: "173.255.215.158 monkinetic.blog www.monkinetic.blog"
            error_page: /usr/share/nginx/html
            autoindex: false
            reverse_proxy:
              locations:
                frontend:
                  location: /
                  proxy_pass: http://goldfrog_server

        upstreams:
          upstream_1:
            name: goldfrog_server
            lb_method: least_conn
            zone_name: frontend
            zone_size: 64k
            sticky_cookie: false
            servers:
              frontend_server_1:
                address: 127.0.0.1
                port: 8080
                weight: 1
                health_check: max_fails=3 fail_timeout=5s