---
    - hosts: webservers

      connection: ssh
      gather_facts: true

      tasks:
        - name: Clone or Update blog content
          # become: yes
          git:
              repo: "{{ content_repo }}"
              dest: "{{ content_location }}"
              update: yes

        - name: Index files
          command: "/usr/bin/goldfrog-indexer --posts_dir {{ content_location }}/posts"
          environment:
              BLOGHOME: "{{ blog_home }}"

        - name: Start or Restart Goldfrog service
          service:
            name: goldfrogd
            enabled: yes
            state: restarted
