---
- name: Converge
  hosts: all
  tasks:
    - name: Install NGINX modules
      include_role:
        name: ansible-role-nginx
      vars:
        nginx_debug_output: true

        nginx_service_modify: true
        nginx_service_timeout: 95
        nginx_selinux: true
        nginx_selinux_tcp_ports:
          - 80
          - 443

        nginx_configure: true
        nginx_cleanup_config: true
        nginx_cleanup_config_paths:
          - directory:
              - /etc/nginx/conf.d
            recurse: false
        nginx_cleanup_config_files:
          - /etc/nginx/conf.d/default.conf

        nginx_modules:
          - brotli
          - geoip
          - image-filter
          - njs
          - perl
          - xslt
