---
- name: Converge
  hosts: all
  tasks:
    - name: Push NGINX config
      include_role:
        name: ansible-role-nginx
      vars:
        nginx_debug_output: true

        nginx_branch: stable
        nginx_main_upload_enable: true
        nginx_main_upload_src: ../files/nginx.conf
        nginx_http_upload_enable: true
        nginx_http_upload_src: ../files/http/*.conf
